import {
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  fetchCat,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_ERROR,
  adoptCat
} from './cat';

import {
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  fetchDog,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_ERROR,
  adoptDog
} from './dog';

export {
  fetchCat, 
  adoptCat, 
  fetchDog, 
  adoptDog,
  FETCH_CAT_REQUEST,
  FETCH_CAT_SUCCESS,
  FETCH_CAT_ERROR,
  ADOPT_CAT_REQUEST,
  ADOPT_CAT_ERROR,
  FETCH_DOG_REQUEST,
  FETCH_DOG_SUCCESS,
  FETCH_DOG_ERROR,
  ADOPT_DOG_REQUEST,
  ADOPT_DOG_ERROR,
}